---
abstract: 'simple session'
author:
  - 'Tokuhiro Matsuno <tokuhirom AAJKLFJEF GMAIL COM>'
build_requires:
  Test::Exception: 0
  Test::More: 0
  YAML: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTTP-Session
no_index:
  directory:
    - inc
    - t
    - examples
requires:
  CGI::Simple::Cookie: 1.103
  Class::Accessor::Fast: 0.31
  Digest::SHA1: 2.11
  HTML::StickyQuery: 0.12
  HTML::StickyQuery::DoCoMoGUID: 0.01
  HTTP::MobileAttribute: 0.07
  HTTP::Response: 5.818
  UNIVERSAL::require: 0.05
  perl: 5.8.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.20
